name: Generate documentation on new tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: html
